version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://user:pass@db:5432/analytics-pro
      - REDIS_URL=redis://redis:6379
      - MAIN_BACKEND_URL=${MAIN_BACKEND_URL:-}
      - MAIN_BACKEND_API_KEY=${MAIN_BACKEND_API_KEY:-}
      - MAIN_BACKEND_JWT=${MAIN_BACKEND_JWT:-}
    depends_on:
      - db
      - redis

  frontend:
    build: ./frontend
    ports:
      - "3004:3000"
    environment:
      - VITE_API_URL=http://localhost:8000

  db:
    image: postgres:15
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=pass
      - POSTGRES_DB=analytics-pro
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine

volumes:
  pgdata:
