[build]
  command = "npx vite build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "18"
  NPM_FLAGS = "--legacy-peer-deps"

# Single Page App Redirects
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
