[build]
  command = "npx vite build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "18"
  NPM_FLAGS = "--legacy-peer-deps"

# Proxy API calls to Render backend
[[redirects]]
  from = "/api/*"
  to = "https://blockchain-forensics-backend.onrender.com/api/:splat"
  status = 200
  force = true

# Single Page App Redirects
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
