[build]
  command = "npx vite build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "18"

# API proxy to Render backend (must come before SPA redirect)
[[redirects]]
  from = "/api/*"
  to = "https://blockchain-forensics-backend.onrender.com/api/:splat"
  status = 200
  force = true

# Security Headers for all routes
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Cross-Origin-Opener-Policy = "same-origin"
    Cross-Origin-Embedder-Policy = "require-corp"
    Cross-Origin-Resource-Policy = "same-site"
    Permissions-Policy = "geolocation=(), microphone=(), camera=(), payment=(), usb=()"
    Strict-Transport-Security = "max-age=31536000; includeSubDomains; preload"

# Single Page App Redirects
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
