services:
  - type: web
    name: blockchain-forensics-backend
    env: docker
    plan: free
    region: oregon
    dockerfilePath: ./Dockerfile.backend
    dockerContext: .
    build:
      args:
        - USE_LITE=1
    autoDeploy: true
    healthCheckPath: /health
    envVars:
      - key: ENVIRONMENT
        value: production
      - key: LOG_LEVEL
        value: INFO
      - key: DEBUG
        value: "false"
      - key: SECRET_KEY
        generateValue: true
      - key: TRUSTED_HOSTS
        value: "[*]"
      - key: CORS_ORIGINS
        value: "[\"*\"]"
      - key: TEST_MODE
        value: "1"
      - key: POSTGRES_URL
        # Empty to trigger TEST_MODE on Free tier (no external DB)
        value: ""
      - key: REDIS_URL
        # Empty to trigger TEST_MODE on Free tier (no external Redis)
        value: ""
      - key: NEO4J_URI
        # Empty to trigger TEST_MODE on Free tier (no external Neo4j)
        value: ""
      - key: NEO4J_USER
        value: "neo4j"
      - key: NEO4J_PASSWORD
        sync: false
      - key: QDRANT_URL
        # Optional: Qdrant Cloud URL or leave unset (client degrades gracefully)
        value: ""
      - key: ENABLE_KAFKA_STREAMING
        value: "0"
      - key: ENABLE_SANCTIONS_WORKER
        value: "0"
      - key: ENABLE_INTEL_FEEDS_WORKER
        value: "0"
      - key: ENABLE_VASP_RISK_WORKER
        value: "0"
      - key: ENABLE_SCHEMA_REGISTRY_BOOTSTRAP
        value: "0"
      - key: ENABLE_MEMPOOL_WS
        value: "0"
      # News & Translation
      - key: ENABLE_NEWS_FEEDS_WORKER
        value: "1"
      - key: NEWS_FEEDS_UPDATE_INTERVAL_MINUTES
        value: "180"
      - key: NEWS_FEEDS_URLS_JSON
        value: '{"chainalysis":"https://blog.chainalysis.com/feed/","coindesk_policy":"https://www.coindesk.com/policy/rss/","elliptic":"https://www.elliptic.co/blog/rss.xml","trm_labs":"https://www.trmlabs.com/blog/rss.xml","theblock_policy":"https://www.theblock.co/rss?category=policy-and-regulation"}'
      - key: TRANSLATION_PROVIDER
        value: "none"
      - key: DEEPL_API_KEY
        sync: false
      - key: GOOGLE_TRANSLATE_API_KEY
        sync: false
      - key: GOOGLE_CLIENT_ID
        # Required for OAuth (see frontend VITE_GOOGLE_CLIENT_ID)
        sync: false
      - key: GOOGLE_CLIENT_SECRET
        sync: false
      - key: OAUTH_CALLBACK_PATH
        value: "/api/v1/auth/oauth/google/callback"
      - key: OPENAI_API_KEY
        # Optional; required for AI chat features
        sync: false
      - key: NOWPAYMENTS_API_KEY
        # Optional; crypto payments
        sync: false
      - key: NOWPAYMENTS_IPN_SECRET
        sync: false
      - key: NOWPAYMENTS_SANDBOX
        value: "true"

      # Social Automation (placeholders; set in Render Dashboard)
      - key: SLACK_WEBHOOK_URL
        sync: false
      - key: DISCORD_WEBHOOK_URL
        sync: false
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: TELEGRAM_WEBHOOK_SECRET
        generateValue: true
      - key: TELEGRAM_DEFAULT_CHAT_ID
        sync: false
      - key: AYRSHARE_API_KEY
        sync: false
      - key: ENABLE_SOCIAL_SCHEDULER
        value: "0"
      - key: SOCIAL_SCHEDULER_INTERVAL_MINUTES
        value: "180"
      - key: SOCIAL_DEFAULT_CHANNELS
        value: "telegram"

  - type: web
    name: appsumo-admin-backend
    env: docker
    plan: free
    region: oregon
    dockerfilePath: ./appsumo-products/admin-backend/backend/Dockerfile
    dockerContext: ./appsumo-products/admin-backend/backend
    autoDeploy: true
    healthCheckPath: /health
    envVars:
      - key: APPSUMO_WEBHOOK_SECRET
        generateValue: true
