services:
  - type: web
    name: blockchain-forensics-backend
    env: docker
    plan: free
    region: oregon
    dockerfilePath: ./Dockerfile.backend
    dockerContext: .
    build:
      args:
        - USE_LITE=1
    autoDeploy: true
    healthCheckPath: /api/healthz
    envVars:
      - key: ENVIRONMENT
        value: production
      - key: LOG_LEVEL
        value: INFO
      - key: DEBUG
        value: "false"
      - key: SECRET_KEY
        generateValue: true
      - key: TRUSTED_HOSTS
        value: "[\"blockchain-forensics-backend.onrender.com\"]"
      - key: CORS_ORIGINS
        value: "[\"https://YOUR_NETLIFY_SITE.netlify.app\"]"
      - key: BACKEND_URL
        value: "https://blockchain-forensics-backend.onrender.com"
      - key: FRONTEND_URL
        value: "https://YOUR_NETLIFY_SITE.netlify.app"
      - key: ENABLE_HSTS
        value: "true"
      - key: FORCE_HTTPS_REDIRECT
        value: "true"
      - key: ENABLE_RATE_LIMIT
        value: "1"
      - key: MAX_REQUEST_SIZE_BYTES
        value: "2097152"
      - key: MIN_API_KEY_LENGTH
        value: "32"
      - key: ENFORCE_2FA_FOR_ADMINS
        value: "0"
      - key: TEST_MODE
        value: "1"
      - key: POSTGRES_URL
        # e.g. from Neon
        value: "postgresql://USER:PASSWORD@HOST:5432/DBNAME"
      - key: REDIS_URL
        # e.g. from Upstash
        value: "rediss://:PASSWORD@HOST:PORT/0"
      - key: NEO4J_URI
        # e.g. AuraDB Free bolt URL
        value: "neo4j+s://YOUR_AURA_HOST:7687"
      - key: NEO4J_USER
        value: "neo4j"
      - key: NEO4J_PASSWORD
        sync: false
      - key: QDRANT_URL
        # Optional: Qdrant Cloud URL or leave unset (client degrades gracefully)
        value: ""
      - key: ENABLE_KAFKA_STREAMING
        value: "0"
      - key: ENABLE_SANCTIONS_WORKER
        value: "0"
      - key: ENABLE_INTEL_FEEDS_WORKER
        value: "0"
      - key: ENABLE_VASP_RISK_WORKER
        value: "0"
      - key: ENABLE_SCHEMA_REGISTRY_BOOTSTRAP
        value: "0"
      - key: ENABLE_MEMPOOL_WS
        value: "0"
      - key: GOOGLE_CLIENT_ID
        # Required for OAuth (see frontend VITE_GOOGLE_CLIENT_ID)
        sync: false
      - key: GOOGLE_CLIENT_SECRET
        sync: false
      - key: OAUTH_CALLBACK_PATH
        value: "/api/v1/auth/oauth/google/callback"
      - key: OPENAI_API_KEY
        # Optional; required for AI chat features
        sync: false
      - key: NOWPAYMENTS_API_KEY
        # Optional; crypto payments
        sync: false
      - key: NOWPAYMENTS_IPN_SECRET
        sync: false
      - key: NOWPAYMENTS_SANDBOX
        value: "true"
      # News & Translation
      - key: ENABLE_NEWS_FEEDS_WORKER
        value: "1"
      - key: NEWS_FEEDS_UPDATE_INTERVAL_MINUTES
        value: "180"
      - key: NEWS_FEEDS_URLS_JSON
        value: '{"chainalysis":"https://blog.chainalysis.com/feed/","coindesk_policy":"https://www.coindesk.com/policy/rss/","elliptic":"https://www.elliptic.co/blog/rss.xml","trm_labs":"https://www.trmlabs.com/blog/rss.xml","theblock_policy":"https://www.theblock.co/rss?category=policy-and-regulation"}'
      - key: TRANSLATION_PROVIDER
        value: "none"
      - key: DEEPL_API_KEY
        sync: false
      - key: GOOGLE_TRANSLATE_API_KEY
        sync: false
