#!/usr/bin/env bash
set -euo pipefail
cat <<'ENV' > .render-env
ENVIRONMENT=production
LOG_LEVEL=INFO
DEBUG=false
SECRET_KEY=__RENDER_GENERATED__
TRUSTED_HOSTS="[*]"
CORS_ORIGINS="[\"*\"]"
POSTGRES_URL=
REDIS_URL=
NEO4J_URI=
NEO4J_USER=neo4j
NEO4J_PASSWORD=
QDRANT_URL=
ENABLE_KAFKA_STREAMING=0
ENABLE_SANCTIONS_WORKER=0
ENABLE_INTEL_FEEDS_WORKER=0
ENABLE_VASP_RISK_WORKER=0
ENABLE_SCHEMA_REGISTRY_BOOTSTRAP=0
ENABLE_MEMPOOL_WS=0
GOOGLE_CLIENT_ID=
GOOGLE_CLIENT_SECRET=
OAUTH_CALLBACK_PATH=/api/v1/auth/oauth/google/callback
OPENAI_API_KEY=
NOWPAYMENTS_API_KEY=
NOWPAYMENTS_IPN_SECRET=
NOWPAYMENTS_SANDBOX=true
ENV
