global:
  resolve_timeout: 5m

route:
  receiver: 'team-platform'
  group_by: ['alertname', 'job']
  group_wait: 30s
  group_interval: 2m
  repeat_interval: 4h
  routes:
  - matchers:
    - component="webhooks"
    - severity="critical"
    receiver: 'team-webhooks-critical'
    continue: true
  - matchers:
    - component="webhooks"
    - severity="warning"
    receiver: 'team-webhooks'
    continue: true
  - matchers:
    - severity="critical"
    receiver: 'team-platform-critical'
    continue: true
  - matchers:
    - severity="warning"
    receiver: 'team-platform'

receivers:
- name: 'team-platform'
  email_configs:
  - to: 'alerts@example.com'
    send_resolved: true
- name: 'team-platform-critical'
  email_configs:
  - to: 'oncall@example.com'
    send_resolved: true
- name: 'team-webhooks'
  slack_configs:
  - api_url: '${SLACK_WEBHOOK_URL}'
    channel: '#webhooks-alerts'
    send_resolved: true
    title: '{{ .CommonLabels.alertname }} ({{ .CommonLabels.severity }})'
    text: 'Service={{ .CommonLabels.service }}, Component={{ .CommonLabels.component }}\n{{ range .Alerts }}- {{ .Annotations.summary }}\n{{ end }}'
  email_configs:
  - to: 'webhooks-alerts@example.com'
    send_resolved: true
- name: 'team-webhooks-critical'
  slack_configs:
  - api_url: '${SLACK_WEBHOOK_CRITICAL_URL}'
    channel: '#webhooks-oncall'
    send_resolved: true
    title: 'CRITICAL: {{ .CommonLabels.alertname }}'
    text: 'Service={{ .CommonLabels.service }}, Component={{ .CommonLabels.component }}\n{{ range .Alerts }}- {{ .Annotations.summary }}\n{{ end }}'
  email_configs:
  - to: 'webhooks-oncall@example.com'
    send_resolved: true
