apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: forensics-metrics-internal
  namespace: blockchain-forensics
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    # Restrict access to Prometheus /metrics: adjust to your cluster CIDRs or Prometheus IP
    nginx.ingress.kubernetes.io/whitelist-source-range: "10.0.0.0/8,172.16.0.0/12,192.168.0.0/16"
spec:
  tls:
    - hosts:
        - api.sigmacode.io
      secretName: api-sigmacode-io-tls
  rules:
    - host: api.sigmacode.io
      http:
        paths:
          - path: /metrics
            pathType: Prefix
            backend:
              service:
                name: backend-service
                port:
                  number: 80
