apiVersion: v1
kind: ConfigMap
metadata:
  name: alertmanager-config
  namespace: blockchain-forensics
  labels:
    app.kubernetes.io/name: alertmanager
    app.kubernetes.io/part-of: monitoring
    app.kubernetes.io/component: alerting
  annotations:
    # Replace emails/webhooks in this config before applying
    kubernetes.io/description: "Alertmanager configuration for Blockchain Forensics"
data:
  alertmanager.yml: |
    global:
      resolve_timeout: 5m
    route:
      receiver: 'team-platform'
      group_by: ['alertname', 'job']
      group_wait: 30s
      group_interval: 2m
      repeat_interval: 4h
      routes:
      - matchers:
        - severity="critical"
        receiver: 'team-platform-critical'
        continue: true
      - matchers:
        - severity="warning"
        receiver: 'team-platform'
    receivers:
    - name: 'team-platform'
      email_configs:
      - to: 'alerts@example.com'
        send_resolved: true
    - name: 'team-platform-critical'
      email_configs:
      - to: 'oncall@example.com'
        send_resolved: true
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: alertmanager
  namespace: blockchain-forensics
  labels:
    app: alertmanager
spec:
  replicas: 1
  selector:
    matchLabels:
      app: alertmanager
  template:
    metadata:
      labels:
        app: alertmanager
    spec:
      containers:
      - name: alertmanager
        image: prom/alertmanager:v0.27.0
        args:
        - "--config.file=/etc/alertmanager/alertmanager.yml"
        - "--storage.path=/alertmanager"
        ports:
        - name: http
          containerPort: 9093
        volumeMounts:
        - name: config
          mountPath: /etc/alertmanager
        - name: data
          mountPath: /alertmanager
        livenessProbe:
          httpGet:
            path: /-/healthy
            port: 9093
          initialDelaySeconds: 10
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /-/ready
            port: 9093
          initialDelaySeconds: 5
          periodSeconds: 5
        resources:
          requests:
            cpu: 50m
            memory: 64Mi
          limits:
            cpu: 200m
            memory: 256Mi
      volumes:
      - name: config
        configMap:
          name: alertmanager-config
          items:
          - key: alertmanager.yml
            path: alertmanager.yml
      - name: data
        emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: alertmanager
  namespace: blockchain-forensics
  labels:
    app: alertmanager
spec:
  type: ClusterIP
  selector:
    app: alertmanager
  ports:
  - name: http
    port: 9093
    targetPort: 9093
