apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: forensics-backend-servicemonitor
  namespace: blockchain-forensics
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      app: forensics-backend
  namespaceSelector:
    matchNames:
      - blockchain-forensics
  endpoints:
    - port: http
      path: /metrics
      interval: 30s
      scrapeTimeout: 10s
      scheme: http
