name: E2E Multilang Tests

on:
  workflow_dispatch: {}
  push:
    branches: [ main ]
    paths:
      - 'frontend/e2e/**'
      - 'frontend/src/**'
      - '.github/workflows/e2e.yml'

jobs:
  e2e:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Playwright
        working-directory: frontend
        run: |
          npm i -D @playwright/test
          npx playwright install --with-deps

      - name: Run E2E (Prod BaseURL)
        working-directory: frontend
        env:
          E2E_BASE_URL: https://forensics.ai
        run: |
          npx playwright test --reporter=list

      - name: Upload Playwright report (if any)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: frontend/playwright-report
          if-no-files-found: ignore
